# Deploying Iris-detection model using Vertex AI

### Install Vertex AI SDK for Python and other required packages

In [1]:
# Vertex SDK for Python
! pip3 install --upgrade --quiet  google-cloud-aiplatform

### Set Google Cloud Project Information

In [2]:
PROJECT_ID = "iitmbs-mlops"
LOCATION = "us-central1"

### Set GCS Information

In [3]:
BUCKET_URI = f"gs://iitmbs-mlops-21f1000344"

### Initialize Vertex AI SDK for Python

In [4]:
from google.cloud import aiplatform

aiplatform.init(project=PROJECT_ID, location=LOCATION, staging_bucket=BUCKET_URI)

### Import the required libraries

In [5]:
import os
import sys

### Setup Git Repository

In [6]:
! git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /home/jupyter/.git/

In [7]:
! git config --global user.email "chandrakarsatvik@gmail.com"

In [8]:
!git config --global user.name "Satvik Chandrakar"

### Install & Configure DVC

In [9]:
! pip3 install dvc dvc-gs

Collecting dvc
  Downloading dvc-3.63.0-py3-none-any.whl.metadata (17 kB)
Collecting dvc-gs
  Downloading dvc_gs-3.0.2-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: attrs>=22.2.0 in /opt/conda/lib/python3.10/site-packages (from dvc) (25.3.0)
Requirement already satisfied: celery in /opt/conda/lib/python3.10/site-packages (from dvc) (5.5.3)
Requirement already satisfied: colorama>=0.3.9 in /opt/conda/lib/python3.10/site-packages (from dvc) (0.4.6)
Collecting configobj>=5.0.9 (from dvc)
  Downloading configobj-5.0.9-py2.py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: distro>=1.3 in /opt/conda/lib/python3.10/site-packages (from dvc) (1.9.0)
Collecting dpath<3,>=2.1.0 (from dvc)
  Downloading dpath-2.2.0-py3-none-any.whl.metadata (15 kB)
Collecting dulwich (from dvc)
  Downloading dulwich-0.24.2-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Collecting dvc-data<3.17,>=3.16.2 (from dvc)
  Downloading dvc_data-3.16.12-py3-none-any.whl.metadata (5.1 kB)
Collecting dvc-http>=2.29.0 (from dvc)
  Downloading dvc_http-2.32.0-py3-none-any.whl.metadata (1.3 kB)
Collecting dvc-objects (from dvc)
  Downloading dvc_objects-5.1.2-py3-none-any.whl.metadata (3.9 kB)
Collecting dvc-render<2,>=1.0.1 (from dvc)
  Downloading dvc_render-1.0.2-py3-none-any.whl.metadata (5.4 kB)
Collecting dvc-studio-client<1,>=0.21 (from dvc)
  Downloading dvc_studio_client-0.22.0-py3-none-any.whl.metadata (4.4 kB)
Collecting dvc-task<1,>=0.3.0 (from dvc)
  Downloading dvc_task-0.40.2-py3-none-any.whl.metadata (10.0 kB)
Collecting flatten_dict<1,>=0.4.1 (from dvc)
  Downloading flatten_dict-0.4.2-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting flufl.lock<9,>=8.1.0 (from dvc)
  Downloading flufl_lock-8.2.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: fsspec>=2024.2.0 in /opt/conda/lib/python3.10/site-packages (from dvc) (2025.9.0)
Collecting funcy>=1.14 (from dvc)
  Downloading funcy-2.0-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting grandalf<1,>=0.7 (from dvc)
  Downloading grandalf-0.8-py3-none-any.whl.metadata (1.7 kB)
Collecting gto<2,>=1.6.0 (from dvc)
  Downloading gto-1.8.0-py3-none-any.whl.metadata (4.7 kB)
Collecting hydra-core>=1.1 (from dvc)
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting iterative-telemetry>=0.0.7 (from dvc)
  Downloading iterative_telemetry-0.0.10-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: kombu in /opt/conda/lib/python3.10/site-packages (from dvc) (5.5.4)
Requirement already satisfied: networkx>=2.5 in /opt/conda/lib/python3.10/site-packages (from dvc) (3.4.2)
Collecting omegaconf (from dvc)
  Downloading omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: packaging>=19 in /opt/conda/lib/python3.10/site-packages (from dvc) (25.0)
Collecting pathspec>=0.10.3 (from dvc)
  Downloading pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: platformdirs<5,>=3.1.1 in /opt/conda/lib/python3.10/site-packages (from dvc) (4.3.8)
Requirement already satisfied: psutil>=5.8 in /opt/conda/lib/python3.10/site-packages (from dvc) (5.9.3)
Collecting pydot>=1.2.4 (from dvc)
  Downloading pydot-4.0.1-py3-none-any.whl.metadata (11 kB)
Collecting pygtrie>=2.3.2 (from dvc)
  Downloading pygtrie-2.5.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: pyparsing>=2.4.7 in /opt/conda/lib/python3.10/site-packages (from dvc) (3.2.4)
Requirement already satisfied: requests>=2.22 in /opt/conda/lib/python3.10/site-packages (from dvc) (2.32.5)
Requirement already satisfied: rich>=12 in /opt/conda/lib/python3.10/site-packages (from dvc) (13.9.4)
Requirement already satisfied: ruamel.yaml>=0.17.11 in /opt/conda/lib/python3.10/site-packages (from dvc) (0.18.15)
Collecting scmrepo<4,>=3.5.2 (from dvc)
  Downloading scmrepo-3.5.2-py3-none-any.whl.metadata (4.8 kB)
Collecting shortuuid>=0.5 (from dvc)
  Downloading shortuuid-1.0.13-py3-none-any.whl.metadata (5.8 kB)
Collecting shtab<2,>=1.3.4 (from dvc)
  Downloading shtab-1.7.2-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: tabulate>=0.8.7 in /opt/conda/lib/python3.10/site-packages (from dvc) (0.9.0)
Collecting tomlkit>=0.11.1 (from dvc)
  Downloading tomlkit-0.13.3-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: tqdm<5,>=4.63.1 in /opt/conda/lib/python3.10/site-packages (from dvc) (4.67.1)
Collecting voluptuous>=0.11.7 (from dvc)
  Downloading voluptuous-0.15.2-py3-none-any.whl.metadata (20 kB)
Collecting zc.lockfile>=1.2.1 (from dvc)
  Downloading zc_lockfile-4.0-py3-none-any.whl.metadata (6.6 kB)
Collecting dictdiffer>=0.8.1 (from dvc-data<3.17,>=3.16.2->dvc)
  Downloading dictdiffer-0.9.0-py2.py3-none-any.whl.metadata (4.8 kB)
Collecting diskcache>=5.2.1 (from dvc-data<3.17,>=3.16.2->dvc)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting sqltrie<1,>=0.11.0 (from dvc-data<3.17,>=3.16.2->dvc)
  Downloading sqltrie-0.11.2-py3-none-any.whl.metadata (3.3 kB)
Collecting orjson<4,>=3 (from dvc-data<3.17,>=3.16.2->dvc)
  Downloading orjson-3.11.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Requirement already satisfied: billiard<5.0,>=4.2.1 in /opt/conda/lib/python3.10/site-packages (from celery->dvc) (4.2.1)
Requirement already satisfied: vine<6.0,>=5.1.0 in /opt/conda/lib/python3.10/site-packages (from celery->dvc) (5.1.0)
Requirement already satisfied: click<9.0,>=8.1.2 in /opt/conda/lib/python3.10/site-packages (from celery->dvc) (8.1.8)
Requirement already satisfied: click-didyoumean>=0.3.0 in /opt/conda/lib/python3.10/site-packages (from celery->dvc) (0.3.1)
Requirement already satisfied: click-repl>=0.2.0 in /opt/conda/lib/python3.10/site-packages (from celery->dvc) (0.3.0)
Requirement already satisfied: click-plugins>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from celery->dvc) (1.1.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from celery->dvc) (2.9.0.post0)
Requirement already satisfied: six<2.0,>=1.12 in /opt/conda/lib/python3.10/site-packages (from flatten_dict<1,>=0.4.1->dvc) (1.17.0)
Requirement already satisfied: atpublic in /opt/conda/lib/python3.10/site-packages (from flufl.lock<9,>=8.1.0->dvc) (5.1)
Requirement already satisfied: entrypoints in /opt/conda/lib/python3.10/site-packages (from gto<2,>=1.6.0->dvc) (0.4)
Requirement already satisfied: pydantic!=2.0.0,<3,>=1.9.0 in /opt/conda/lib/python3.10/site-packages (from gto<2,>=1.6.0->dvc) (2.11.9)
Collecting semver>=2.13.0 (from gto<2,>=1.6.0->dvc)
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Collecting typer>=0.4.1 (from gto<2,>=1.6.0->dvc)
  Downloading typer-0.19.2-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: amqp<6.0.0,>=5.1.1 in /opt/conda/lib/python3.10/site-packages (from kombu->dvc) (5.3.1)
Requirement already satisfied: tzdata>=2025.2 in /opt/conda/lib/python3.10/site-packages (from kombu->dvc) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.10/site-packages (from pydantic!=2.0.0,<3,>=1.9.0->gto<2,>=1.6.0->dvc) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /opt/conda/lib/python3.10/site-packages (from pydantic!=2.0.0,<3,>=1.9.0->gto<2,>=1.6.0->dvc) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/conda/lib/python3.10/site-packages (from pydantic!=2.0.0,<3,>=1.9.0->gto<2,>=1.6.0->dvc) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /opt/conda/lib/python3.10/site-packages (from pydantic!=2.0.0,<3,>=1.9.0->gto<2,>=1.6.0->dvc) (0.4.1)
Requirement already satisfied: gitpython>3 in /opt/conda/lib/python3.10/site-packages (from scmrepo<4,>=3.5.2->dvc) (3.1.45)
Collecting pygit2>=1.14.0 (from scmrepo<4,>=3.5.2->dvc)
  Downloading pygit2-1.18.2-cp310-cp310-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (3.6 kB)
Collecting asyncssh<3,>=2.13.1 (from scmrepo<4,>=3.5.2->dvc)
  Downloading asyncssh-2.21.1-py3-none-any.whl.metadata (9.9 kB)
Collecting aiohttp-retry>=2.5.0 (from scmrepo<4,>=3.5.2->dvc)
  Downloading aiohttp_retry-2.9.1-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: cryptography>=39.0 in /opt/conda/lib/python3.10/site-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (45.0.7)
Requirement already satisfied: gcsfs>=2022.11.0 in /opt/conda/lib/python3.10/site-packages (from dvc-gs) (2025.9.0)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (3.12.15)
Requirement already satisfied: prompt-toolkit>=3.0.36 in /opt/conda/lib/python3.10/site-packages (from click-repl>=0.2.0->celery->dvc) (3.0.52)
Requirement already satisfied: cffi>=1.14 in /opt/conda/lib/python3.10/site-packages (from cryptography>=39.0->asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (1.17.1)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.10/site-packages (from cffi>=1.14->cryptography>=39.0->asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (2.22)
Requirement already satisfied: urllib3>=2.2.2 in /opt/conda/lib/python3.10/site-packages (from dulwich->dvc) (2.5.0)
Requirement already satisfied: decorator>4.1.2 in /opt/conda/lib/python3.10/site-packages (from gcsfs>=2022.11.0->dvc-gs) (5.2.1)
Requirement already satisfied: google-auth>=1.2 in /opt/conda/lib/python3.10/site-packages (from gcsfs>=2022.11.0->dvc-gs) (2.40.3)
Requirement already satisfied: google-auth-oauthlib in /opt/conda/lib/python3.10/site-packages (from gcsfs>=2022.11.0->dvc-gs) (1.2.2)
Requirement already satisfied: google-cloud-storage in /opt/conda/lib/python3.10/site-packages (from gcsfs>=2022.11.0->dvc-gs) (2.19.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (5.0.1)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (1.20.1)
Requirement already satisfied: idna>=2.0 in /opt/conda/lib/python3.10/site-packages (from yarl<2.0,>=1.17.0->aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (3.10)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/conda/lib/python3.10/site-packages (from gitpython>3->scmrepo<4,>=3.5.2->dvc) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/conda/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->gitpython>3->scmrepo<4,>=3.5.2->dvc) (5.0.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from google-auth>=1.2->gcsfs>=2022.11.0->dvc-gs) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.10/site-packages (from google-auth>=1.2->gcsfs>=2022.11.0->dvc-gs) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.10/site-packages (from google-auth>=1.2->gcsfs>=2022.11.0->dvc-gs) (4.9.1)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/conda/lib/python3.10/site-packages (from rsa<5,>=3.1.4->google-auth>=1.2->gcsfs>=2022.11.0->dvc-gs) (0.6.1)
Collecting antlr4-python3-runtime==4.9.* (from hydra-core>=1.1->dvc)
  Downloading antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: PyYAML>=5.1.0 in /opt/conda/lib/python3.10/site-packages (from omegaconf->dvc) (6.0.2)
Collecting appdirs (from iterative-telemetry>=0.0.7->dvc)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from iterative-telemetry>=0.0.7->dvc) (3.19.1)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.10/site-packages (from prompt-toolkit>=3.0.36->click-repl>=0.2.0->celery->dvc) (0.2.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests>=2.22->dvc) (3.4.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests>=2.22->dvc) (2025.8.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.10/site-packages (from rich>=12->dvc) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.10/site-packages (from rich>=12->dvc) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=12->dvc) (0.1.2)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in /opt/conda/lib/python3.10/site-packages (from ruamel.yaml>=0.17.11->dvc) (0.2.12)
Collecting shellingham>=1.3.0 (from typer>=0.4.1->gto<2,>=1.6.0->dvc)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.10/site-packages (from zc.lockfile>=1.2.1->dvc) (80.9.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from google-auth-oauthlib->gcsfs>=2022.11.0->dvc-gs) (2.0.0)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/conda/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gcsfs>=2022.11.0->dvc-gs) (3.3.1)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.15.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-storage->gcsfs>=2022.11.0->dvc-gs) (2.25.1)
Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-storage->gcsfs>=2022.11.0->dvc-gs) (2.4.3)
Requirement already satisfied: google-resumable-media>=2.7.2 in /opt/conda/lib/python3.10/site-packages (from google-cloud-storage->gcsfs>=2022.11.0->dvc-gs) (2.7.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-storage->gcsfs>=2022.11.0->dvc-gs) (1.7.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /opt/conda/lib/python3.10/site-packages (from google-api-core<3.0.0dev,>=2.15.0->google-cloud-storage->gcsfs>=2022.11.0->dvc-gs) (1.70.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /opt/conda/lib/python3.10/site-packages (from google-api-core<3.0.0dev,>=2.15.0->google-cloud-storage->gcsfs>=2022.11.0->dvc-gs) (6.31.1)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /opt/conda/lib/python3.10/site-packages (from google-api-core<3.0.0dev,>=2.15.0->google-cloud-storage->gcsfs>=2022.11.0->dvc-gs) (1.26.1)
Downloading dvc-3.63.0-py3-none-any.whl (466 kB)
Downloading dpath-2.2.0-py3-none-any.whl (17 kB)
Downloading dvc_data-3.16.12-py3-none-any.whl (78 kB)
Downloading dvc_objects-5.1.2-py3-none-any.whl (33 kB)
Downloading dvc_render-1.0.2-py3-none-any.whl (22 kB)
Downloading dvc_studio_client-0.22.0-py3-none-any.whl (16 kB)
Downloading dvc_task-0.40.2-py3-none-any.whl (21 kB)
Downloading flatten_dict-0.4.2-py2.py3-none-any.whl (9.7 kB)
Downloading flufl_lock-8.2.0-py3-none-any.whl (11 kB)
Downloading grandalf-0.8-py3-none-any.whl (41 kB)
Downloading gto-1.8.0-py3-none-any.whl (45 kB)
Downloading orjson-3.11.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (132 kB)
Downloading scmrepo-3.5.2-py3-none-any.whl (73 kB)
Downloading asyncssh-2.21.1-py3-none-any.whl (375 kB)
Downloading shtab-1.7.2-py3-none-any.whl (14 kB)
Downloading sqltrie-0.11.2-py3-none-any.whl (17 kB)
Downloading dvc_gs-3.0.2-py3-none-any.whl (10 kB)
Downloading aiohttp_retry-2.9.1-py3-none-any.whl (10.0 kB)
Downloading configobj-5.0.9-py2.py3-none-any.whl (35 kB)
Downloading dictdiffer-0.9.0-py2.py3-none-any.whl (16 kB)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
Downloading dulwich-0.24.2-cp310-cp310-manylinux_2_28_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 25.2 MB/s  0:00:00
Downloading dvc_http-2.32.0-py3-none-any.whl (12 kB)
Downloading funcy-2.0-py2.py3-none-any.whl (30 kB)
Downloading hydra_core-1.3.2-py3-none-any.whl (154 kB)
Downloading omegaconf-2.3.0-py3-none-any.whl (79 kB)
Downloading iterative_telemetry-0.0.10-py3-none-any.whl (10 kB)
Downloading pathspec-0.12.1-py3-none-any.whl (31 kB)
Downloading pydot-4.0.1-py3-none-any.whl (37 kB)
Downloading pygit2-1.18.2-cp310-cp310-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 65.1 MB/s  0:00:00
Downloading pygtrie-2.5.0-py3-none-any.whl (25 kB)
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Downloading shortuuid-1.0.13-py3-none-any.whl (10 kB)
Downloading tomlkit-0.13.3-py3-none-any.whl (38 kB)
Downloading typer-0.19.2-py3-none-any.whl (46 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading voluptuous-0.15.2-py3-none-any.whl (31 kB)
Downloading zc_lockfile-4.0-py3-none-any.whl (9.1 kB)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Building wheels for collected packages: antlr4-python3-runtime
  DEPRECATION: Building 'antlr4-python3-runtime' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'antlr4-python3-runtime'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144591 sha256=bde3915e7803f68af1b18c349378a9a93bfde7d46d426a86aaf16234451a3f20
  Stored in directory: /home/jupyter/.cache/pip/wheels/12/93/dd/1f6a127edc45659556564c5730f6d4e300888f4bca2d4c5a88
Successfully built antlr4-python3-runtime
Installing collected packages: pygtrie, funcy, dictdiffer, appdirs, antlr4-python3-runtime, zc.lockfile, voluptuous, tomlkit, shtab, shortuuid, shellingham, semver, pydot, pathspec, orjson, omegaconf, grandalf, flufl.lock, flatten_dict, dvc-render, dvc-objects, dulwich, dpath, diskcache, configobj, sqltrie, pygit2, iterative-telemetry, hydra-core, dvc-studio-client, typer, dvc-data, asyncssh, dvc-task, aiohttp-retry, scmrepo, dvc-http, gto, dvc, dvc-gs
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40/40 [dvc-gs]38/40 [dvc]http]e]]n3-runtime]
Successfully installed aiohttp-retry-2.9.1 antlr4-python3-runtime-4.9.3 appdirs-1.4.4 asyncssh-2.21.1 configobj-5.0.9 dictdiffer-0.9.0 diskcache-5.6.3 dpath-2.2.0 dulwich-0.24.2 dvc-3.63.0 dvc-data-3.16.12 dvc-gs-3.0.2 dvc-http-2.32.0 dvc-objects-5.1.2 dvc-render-1.0.2 dvc-studio-client-0.22.0 dvc-task-0.40.2 flatten_dict-0.4.2 flufl.lock-8.2.0 funcy-2.0 grandalf-0.8 gto-1.8.0 hydra-core-1.3.2 iterative-telemetry-0.0.10 omegaconf-2.3.0 orjson-3.11.3 pathspec-0.12.1 pydot-4.0.1 pygit2-1.18.2 pygtrie-2.5.0 scmrepo-3.5.2 semver-3.0.4 shellingham-1.5.4 shortuuid-1.0.13 shtab-1.7.2 sqltrie-0.11.2 tomlkit-0.13.3 typer-0.19.2 voluptuous-0.15.2 zc.lockfile-4.0

In [10]:
! dvc init

Initialized DVC repository.

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/iterative/dvc>

In [11]:
! git add .dvc

### Configure GCS as Remote Storage

In [12]:
! dvc remote add -d myremote {BUCKET_URI}

Setting 'myremote' as a default remote.

In [13]:
! dvc remote modify myremote credentialpath iitmbs-mlops-0be300234da6.json

In [14]:
! git add .dvc/config

## Simple Decision Tree model
Build a Decision Tree model on iris data

In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from pandas.plotting import parallel_coordinates
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import metrics
from sklearn.metrics import accuracy_score

### Load Data

In [16]:
data = pd.read_csv('data/iris.csv')
data.head(5)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [17]:
data.shape

(150, 5)

### Track Data with DVC

In [18]:
! dvc add data/iris.csv

 ⠋ Checking graph
Adding...
!
Collecting files and computing hashes in data/iris.csv |0.00 [00:00,     ?file/s

!
  0% Checking cache in '/home/jupyter/.dvc/cache/files/md5'| |0/? [00:00<?,    ?

!
  0%|          |Adding data/iris.csv to cache         0/1 [00:00<?,     ?file/s]

!
  0%|          |Checking out /home/jupyter/data/iris.c0/1 [00:00<?,    ?files/s]
100% Adding...|████████████████████████████████████████|1/1 [00:00, 15.76file/s]

To track the changes with git, run:

	git add data/.gitignore data/iris.csv.dvc

To enable auto staging, run:

	dvc config core.autostage true

In [19]:
! git add data/.gitignore data/iris.csv.dvc

In [20]:
! dvc push

Collecting                                            |1.00 [00:00,  141entry/s]
Pushing
!
  0% Checking cache in 'iitmbs-mlops-21f1000344/files/md5'| |0/? [00:00<?,    ?f

!
  0% Checking cache in '/home/jupyter/.dvc/cache/files/md5'| |0/? [00:00<?,    ?

!
  0%|          |Pushing to gs                         0/1 [00:00<?,     ?file/s]

!

  0%|          |/home/jupyter/.dvc/cache/files/0.00/3.77k [00:00<?,        ?B/s]

100%|██████████|/home/jupyter/.dvc/cache/f3.77k/3.77k [00:00<00:00,    32.7kB/s]


100%|██████████|Pushing to gs                     1/1 [00:00<00:00,  5.54file/s]
Pushing
1 file pushed

### Train Model

In [21]:
train, test = train_test_split(data, test_size = 0.2, stratify = data['species'], random_state = 42)
X_train = train[['sepal_length','sepal_width','petal_length','petal_width']]
y_train = train.species
X_test = test[['sepal_length','sepal_width','petal_length','petal_width']]
y_test = test.species

In [22]:
mod_dt = DecisionTreeClassifier(max_depth = 3, random_state = 1)
mod_dt.fit(X_train,y_train)
prediction=mod_dt.predict(X_test)
print('The accuracy of the Decision Tree is',"{:.3f}".format(metrics.accuracy_score(prediction,y_test)))

The accuracy of the Decision Tree is 0.967

In [23]:
# Save model locally
import joblib

joblib.dump(mod_dt, f"artifacts/model.joblib")

['artifacts/model.joblib']

### Track Model with DVC

In [24]:
! dvc add artifacts/model.joblib

 ⠋ Checking graph
Adding...
!
Collecting files and computing hashes in artifacts/model.joblib |0.00 [00:00,

!
  0% Checking cache in '/home/jupyter/.dvc/cache/files/md5'| |0/? [00:00<?,    ?

!
  0%|          |Adding artifacts/model.joblib to cache0/1 [00:00<?,     ?file/s]

!
  0%|          |Checking out /home/jupyter/artifacts/m0/1 [00:00<?,    ?files/s]
100% Adding...|████████████████████████████████████████|1/1 [00:00, 23.82file/s]

To track the changes with git, run:

	git add artifacts/model.joblib.dvc artifacts/.gitignore

To enable auto staging, run:

	dvc config core.autostage true

In [25]:
! git add artifacts/model.joblib.dvc artifacts/.gitignore

In [26]:
! dvc push

Collecting                                            |2.00 [00:00,  163entry/s]
Pushing
!
  0% Checking cache in 'iitmbs-mlops-21f1000344/files/md5'| |0/? [00:00<?,    ?f
 50% Querying cache in 'iitmbs-mlops-21f1000344/files/md5'|▌|1/2 [00:00<00:00,

!
  0% Checking cache in '/home/jupyter/.dvc/cache/files/md5'| |0/? [00:00<?,    ?

!
  0%|          |Pushing to gs                         0/1 [00:00<?,     ?file/s]

!

  0%|          |/home/jupyter/.dvc/cache/files/0.00/2.50k [00:00<?,        ?B/s]

100%|██████████|/home/jupyter/.dvc/cache/f2.50k/2.50k [00:00<00:00,    21.4kB/s]


100%|██████████|Pushing to gs                     1/1 [00:00<00:00,  6.55file/s]
Pushing
1 file pushed

In [27]:
! git commit -m "First iteration done with 150 rows of iris data"

[master (root-commit) 6279bcd] First iteration done with 150 rows of iris data
 7 files changed, 23 insertions(+)
 create mode 100644 .dvc/.gitignore
 create mode 100644 .dvc/config
 create mode 100644 .dvcignore
 create mode 100644 artifacts/.gitignore
 create mode 100644 artifacts/model.joblib.dvc
 create mode 100644 data/.gitignore
 create mode 100644 data/iris.csv.dvc

In [28]:
! git tag -a "v1.0" -m "model v1.0, 150 rows of data"

### Simulate Data Additions

In [29]:
# Simulate augmentation by duplicating with noise
augmented = data.copy()
augmented["sepal_length"] = augmented["sepal_length"] + 0.1
augmented["species"] = augmented["species"]

# Merge
data = pd.concat([data, augmented], ignore_index=True)

# Save new version
data.to_csv("data/iris.csv", index=False)

In [30]:
data.shape

(300, 5)

### Track Data Version 2 with DVC

In [31]:
! dvc add data/iris.csv

 ⠋ Checking graph
Adding...
!
Collecting files and computing hashes in data/iris.csv |0.00 [00:00,     ?file/s

!
  0% Checking cache in '/home/jupyter/.dvc/cache/files/md5'| |0/? [00:00<?,    ?

!
  0%|          |Adding data/iris.csv to cache         0/1 [00:00<?,     ?file/s]

!
  0%|          |Checking out /home/jupyter/data/iris.c0/1 [00:00<?,    ?files/s]
100% Adding...|████████████████████████████████████████|1/1 [00:00, 22.60file/s]

To track the changes with git, run:

	git add data/iris.csv.dvc

To enable auto staging, run:

	dvc config core.autostage true

In [32]:
! git add data/.gitignore data/iris.csv.dvc

In [33]:
! dvc push

Collecting                                            |2.00 [00:00,  119entry/s]
Pushing
!
  0% Checking cache in 'iitmbs-mlops-21f1000344/files/md5'| |0/? [00:00<?,    ?f
 50% Querying cache in 'iitmbs-mlops-21f1000344/files/md5'|▌|1/2 [00:00<00:00,

!
  0% Checking cache in '/home/jupyter/.dvc/cache/files/md5'| |0/? [00:00<?,    ?

!
  0%|          |Pushing to gs                         0/1 [00:00<?,     ?file/s]

!

  0%|          |/home/jupyter/.dvc/cache/files/0.00/8.27k [00:00<?,        ?B/s]

100%|██████████|/home/jupyter/.dvc/cache/f8.27k/8.27k [00:00<00:00,    69.1kB/s]


100%|██████████|Pushing to gs                     1/1 [00:00<00:00,  6.01file/s]
Pushing
1 file pushed

### Train Model with Data Version 2

In [34]:
train, test = train_test_split(data, test_size = 0.2, stratify = data['species'], random_state = 42)
X_train = train[['sepal_length','sepal_width','petal_length','petal_width']]
y_train = train.species
X_test = test[['sepal_length','sepal_width','petal_length','petal_width']]
y_test = test.species

In [35]:
mod_dt = DecisionTreeClassifier(max_depth = 3, random_state = 1)
mod_dt.fit(X_train,y_train)
prediction=mod_dt.predict(X_test)
print('The accuracy of the Decision Tree is',"{:.3f}".format(metrics.accuracy_score(prediction,y_test)))

The accuracy of the Decision Tree is 0.933

In [36]:
# Save model locally
import joblib

joblib.dump(mod_dt, f"artifacts/model.joblib")

['artifacts/model.joblib']

### Track Model with DVC

In [37]:
! dvc add artifacts/model.joblib

 ⠋ Checking graph
Adding...
!
Collecting files and computing hashes in artifacts/model.joblib |0.00 [00:00,

!
  0% Checking cache in '/home/jupyter/.dvc/cache/files/md5'| |0/? [00:00<?,    ?

!
  0%|          |Adding artifacts/model.joblib to cache0/1 [00:00<?,     ?file/s]

!
  0%|          |Checking out /home/jupyter/artifacts/m0/1 [00:00<?,    ?files/s]
100% Adding...|████████████████████████████████████████|1/1 [00:00, 23.99file/s]

To track the changes with git, run:

	git add artifacts/model.joblib.dvc

To enable auto staging, run:

	dvc config core.autostage true

In [38]:
! git add artifacts/model.joblib.dvc artifacts/.gitignore

In [39]:
! dvc push

Collecting                                            |2.00 [00:00,  151entry/s]
Pushing
!
  0% Checking cache in 'iitmbs-mlops-21f1000344/files/md5'| |0/? [00:00<?,    ?f
 50% Querying cache in 'iitmbs-mlops-21f1000344/files/md5'|▌|1/2 [00:00<00:00,

!
  0% Checking cache in '/home/jupyter/.dvc/cache/files/md5'| |0/? [00:00<?,    ?

!
  0%|          |Pushing to gs                         0/1 [00:00<?,     ?file/s]

!

  0%|          |/home/jupyter/.dvc/cache/files/0.00/2.50k [00:00<?,        ?B/s]

100%|██████████|/home/jupyter/.dvc/cache/f2.50k/2.50k [00:00<00:00,    21.5kB/s]


100%|██████████|Pushing to gs                     1/1 [00:00<00:00,  6.14file/s]
Pushing
1 file pushed

In [40]:
! git commit -m "second iteration done with 300 rows of iris data"

[master 1e65e55] second iteration done with 300 rows of iris data
 2 files changed, 3 insertions(+), 3 deletions(-)

In [41]:
! git tag -a "v2.0" -m "model v2.0, 300 rows of data"

### Version Traversal with `dvc checkout`

In [49]:
!git checkout v2.0
!dvc checkout

Previous HEAD position was 6279bcd First iteration done with 150 rows of iris data
HEAD is now at 1e65e55 second iteration done with 300 rows of iris data
Building workspace index                              |4.00 [00:00, 14.7entry/s]
Comparing indexes                                    |5.00 [00:00, 1.30kentry/s]
Applying changes                                      |2.00 [00:00,   406file/s]
M       artifacts/model.joblib
M       data/iris.csv

In [50]:
data = pd.read_csv('data/iris.csv')
data.shape

(300, 5)

In [51]:
data.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
295           6.8          3.0           5.2          2.3  virginica
296           6.4          2.5           5.0          1.9  virginica
297           6.6          3.0           5.2          2.0  virginica
298           6.3          3.4           5.4          2.3  virginica
299           6.0          3.0           5.1          1.8  virginica

In [52]:
train, test = train_test_split(data, test_size = 0.2, stratify = data['species'], random_state = 42)
X_train = train[['sepal_length','sepal_width','petal_length','petal_width']]
y_train = train.species
X_test = test[['sepal_length','sepal_width','petal_length','petal_width']]
y_test = test.species

In [53]:
X_train.shape

(240, 4)

In [54]:
X_test.shape

(60, 4)

In [55]:
model = joblib.load("artifacts/model.joblib")
y_pred = model.predict(X_test)
print("Eval Accuracy:", accuracy_score(y_test, y_pred))

Eval Accuracy: 0.9333333333333333